### ISSUE TITLE
Create testing infrastructure

### ISSUE THREAD

**Issue by techsavy-ntsprint** [techsavyntsprint/netcore-api#1]
We need to increment unit test coverage.

**Comment by jbnone** [comment]
@techsavy-ntsprint could we reduce the scope of this issue? Maybe breaking it down into smaller issues, I'm thinking of something like this:

- Create testing infrastructure (Configure a testing framework, in memory database, etc.)
- Add unit tests coverage for core layer.
- Add unit tests coverage for service layer.

**Comment by techsavy-ntsprint** [comment]
@jbermudezcabrera please feel free to break it down.
